// TEMPORARY DATA

export const role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Jasur Bek",
    email: "john@maktab.uz",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Matematika", "Geometriya"],
    classes: ["1B", "2A", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Dilnoza Karimova",
    email: "jane@maktab.uz",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Fizika", "Kimyo"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Murod G'ani",
    email: "mike@maktab.uz",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biologiya"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jamshid Farhod",
    email: "jay@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Tarix"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Sevara Islomova",
    email: "jane@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Musiqa", "Tarix"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anora Sattorova",
    email: "anna@maktab.uz",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Fizika"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Alisher Qodirov",
    email: "allen@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Ingliz tili", "Ispan tili"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Oydin Karimova",
    email: "ophelia@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Matematika", "Geometriya"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Diyor Bek",
    email: "derek@maktab.uz",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Adabiyot", "Ingliz tili"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Jahongir G'ani",
    email: "john@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biologiya"],
    classes: ["5A", "4B", "3C"],
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Jasur Bek",
    email: "john@maktab.uz",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Dilnoza Karimova",
    email: "jane@maktab.uz",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Murod G'ani",
    email: "mike@maktab.uz",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jamshid Farhod",
    email: "jay@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Sevara Islomova",
    email: "jane@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anora Sattorova",
    email: "anna@maktab.uz",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Alisher Qodirov",
    email: "allen@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Oydin Karimova",
    email: "ophelia@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Diyor Bek",
    email: "derek@maktab.uz",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Jahongir G'ani",
    email: "john@maktab.uz",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Jasur Bek",
    students: ["Sarvinoz Baraka"],
    email: "john@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 2,
    name: "Dilnoza Karimova",
    students: ["Sitora Bredli"],
    email: "jane@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 3,
    name: "Murod G'ani",
    students: ["Feruza Koldvel"],
    email: "mike@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 4,
    name: "Jamshid Farhod",
    students: ["Malika Fitsjerald", "Islom Briant"],
    email: "mike@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 5,
    name: "Sevara Islomova",
    students: ["Maftuna Xarvi"],
    email: "mike@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 6,
    name: "Anora Sattorova",
    students: ["Javlon Lamber"],
    email: "mike@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 7,
    name: "Alisher Qodirov",
    students: ["Kamola Taker", "Lola Anderwood"],
    email: "mike@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 8,
    name: "Oydin Karimova",
    students: ["Alisher Bleyr"],
    email: "mike@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 9,
    name: "Diyor Bek",
    students: ["Sanobar Vebster", "Malika Stoun"],
    email: "mike@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
  {
    id: 10,
    name: "Jahongir G'ani",
    students: ["Saida Skott"],
    email: "mike@maktab.uz",
    phone: "1234567890",
    address: "Toshkent, Mustaqillik ko'chasi, 12-uy",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Matematika",
    teachers: ["Zarina Po'latova", "Rustam Davronov"],
  },
  {
    id: 2,
    name: "Ingliz tili",
    teachers: ["Mansur Bekker", "Elyor Chavvez"],
  },
  {
    id: 3,
    name: "Fizika",
    teachers: ["Lola Navoiy", "Doston Delgodo"],
  },
  {
    id: 4,
    name: "Kimyo",
    teachers: ["Nodir Kelli", "Bekzod Snydar"],
  },
  {
    id: 5,
    name: "Biologiya",
    teachers: ["Almira Bens", "Lina Qoliyor"],
  },
  {
    id: 6,
    name: "Tarix",
    teachers: ["Hanna Bo'man", "Bibi O'brien"],
  },
  {
    id: 7,
    name: "Geografiya",
    teachers: ["Lola Farhod", "Suyun Brediy"],
  },
  {
    id: 8,
    name: "Tasviriy san'at",
    teachers: ["Hulkar Alvarado", "Mahliyo Keller"],
  },
  {
    id: 9,
    name: "Musiqa",
    teachers: ["Gulru Roy", "Roza Singlton"],
  },
  {
    id: 10,
    name: "Adabiyot",
    teachers: ["Ezoza Linch", "Bahrom Flauers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Jasur Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Bekzod Jozeph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Temur Bennet",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Akmal Kollinz",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iroda Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Laylo Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Kamola Uolton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Komil Batler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Murod Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Oydin Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Matematika",
    class: "1A",
    teacher: "Tohir Vays",
  },
  {
    id: 2,
    subject: "Ingliz tili",
    class: "2A",
    teacher: "Ra'no Frank",
  },
  {
    id: 3,
    subject: "Tabiiy fanlar",
    class: "3A",
    teacher: "Dilnoza Don",
  },
  {
    id: 4,
    subject: "Ijtimoiy fanlar",
    class: "1B",
    teacher: "Bekzod Rodriges",
  },
  {
    id: 5,
    subject: "Tasviriy san'at",
    class: "4A",
    teacher: "Bahor Batler",
  },
  {
    id: 6,
    subject: "Musiqa",
    class: "5A",
    teacher: "Madina Oliver",
  },
  {
    id: 7,
    subject: "Tarix",
    class: "6A",
    teacher: "Husan Hovard",
  },
  {
    id: 8,
    subject: "Geografiya",
    class: "6B",
    teacher: "Lobar Tomas",
  },
  {
    id: 9,
    subject: "Fizika",
    class: "6C",
    teacher: "Rustam Roberts",
  },
  {
    id: 10,
    subject: "Kimyo",
    class: "4B",
    teacher: "Jasmina Pitman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Matematika",
    class: "1A",
    teacher: "Marhabo Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "Ingliz tili",
    class: "2A",
    teacher: "Ravshan Garsiya",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Tabiiy fanlar",
    class: "3A",
    teacher: "Marjona Skott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Ijtimoiy fanlar",
    class: "1B",
    teacher: "Alisher Svanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Tasviriy san'at",
    class: "4A",
    teacher: "Mavluda Vallis",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Musiqa",
    class: "5A",
    teacher: "Dilshod Tomson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "Tarix",
    class: "6A",
    teacher: "Aliya Konner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geografiya",
    class: "6B",
    teacher: "Humoyun Fullar",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Fizika",
    class: "7A",
    teacher: "Laylo Lindsi",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Kimyo",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Matematika",
    class: "1A",
    teacher: "Aziz Bun",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "Ingliz tili",
    class: "2A",
    teacher: "Komil Bouen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Tabiiy fanlar",
    class: "3A",
    teacher: "Kamola Meloun",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Ijtimoiy fanlar",
    class: "1B",
    teacher: "Valijon Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Tasviriy san'at",
    class: "4A",
    teacher: "Jasur Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Musiqa",
    class: "5A",
    teacher: "Karina Ovens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "Tarix",
    class: "6A",
    teacher: "Sherzod Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geografiya",
    class: "6B",
    teacher: "Doniyor Hollouey",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Fizika",
    class: "7A",
    teacher: "Farrux Gregori",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Kimyo",
    class: "8A",
    teacher: "Daniyar Nguen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Matematika",
    class: "1A",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "Ingliz tili",
    class: "2A",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Tabiiy fanlar",
    class: "3A",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Ijtimoiy fanlar",
    class: "1B",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Tasviriy san'at",
    class: "4A",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Musiqa",
    class: "5A",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "Tarix",
    class: "6A",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geografiya",
    class: "6B",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Fizika",
    class: "7A",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Kimyo",
    class: "8A",
    teacher: "Jasur Bek",
    student: "Jasur Bek",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Ko'l sayohati",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Piknik",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Plyaj sayohati",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Muzey sayohati",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Musiqa konserti",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Sehrgar shousi",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Ko'l sayohati",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Velosiped poygasi",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Tasviriy san'at ko'rgazmasi",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sport musobaqasi",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "4A Matematika testi",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "3A Matematika testi",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "3B Matematika testi",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "6A Matematika testi",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "8C Matematika testi",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "2A Matematika testi",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "4C Matematika testi",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "4B Matematika testi",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "3C Matematika testi",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "1C Matematika testi",
    class: "1C",
    date: "2025-01-01",
  },
];

export const attendanceData = [
  {
    id: 1,
    student: "Jasur Bek",
    class: "1A",
    date: "2025-01-15",
    status: "present",
  },
  {
    id: 2,
    student: "Dilnoza Karimova",
    class: "5A",
    date: "2025-01-15",
    status: "present",
  },
  {
    id: 3,
    student: "Murod G'ani",
    class: "5A",
    date: "2025-01-15",
    status: "absent",
  },
  {
    id: 4,
    student: "Jamshid Farhod",
    class: "5A",
    date: "2025-01-15",
    status: "present",
  },
  {
    id: 5,
    student: "Sevara Islomova",
    class: "5A",
    date: "2025-01-15",
    status: "late",
  },
  {
    id: 6,
    student: "Anora Sattorova",
    class: "5A",
    date: "2025-01-15",
    status: "present",
  },
  {
    id: 7,
    student: "Alisher Qodirov",
    class: "5A",
    date: "2025-01-15",
    status: "present",
  },
  {
    id: 8,
    student: "Oydin Karimova",
    class: "5A",
    date: "2025-01-15",
    status: "absent",
  },
  {
    id: 9,
    student: "Diyor Bek",
    class: "5A",
    date: "2025-01-15",
    status: "present",
  },
  {
    id: 10,
    student: "Jahongir G'ani",
    class: "5A",
    date: "2025-01-15",
    status: "late",
  },
];

export const messagesData = [
  {
    id: 1,
    sender: "Jasur Bek",
    recipient: "Sevara Islomova",
    subject: "Matematika topshirig'i savoli",
    message: "Assalomu alaykum, keyingi haftadagi matematika topshirig'i haqida savolim bor.",
    date: "2025-01-10",
    status: "read",
  },
  {
    id: 2,
    sender: "Sevara Islomova",
    recipient: "Jasur Bek",
    subject: "Re: Matematika topshirig'i savoli",
    message: "Albatta, yordam beraman. Qaysi joyi qiyin bo'lyapti?",
    date: "2025-01-11",
    status: "read",
  },
  {
    id: 3,
    sender: "Murod G'ani",
    recipient: "Tohir Vays",
    subject: "Davomat bo'yicha xabar",
    message: "Hurmatli ustoz, ertaga shifokor qabuliga borishim sababli darsga kelolmayman.",
    date: "2025-01-12",
    status: "unread",
  },
  {
    id: 4,
    sender: "Sarvinoz Admin",
    recipient: "Barcha o'qituvchilar",
    subject: "Xodimlar yig'ilishi eslatmasi",
    message: "Eslatma: Juma kuni soat 15:00 da yig'ilish bo'ladi.",
    date: "2025-01-13",
    status: "read",
  },
  {
    id: 5,
    sender: "Ota-onalar qo'mitasi",
    recipient: "Barcha ota-onalar",
    subject: "Keyingi oy maktab tadbiri",
    message: "Keyingi oy maktab yarmarkasi bo'lib o'tadi.",
    date: "2025-01-14",
    status: "unread",
  },
  {
    id: 6,
    sender: "Jamshid Farhod",
    recipient: "Ra'no Frank",
    subject: "Loyiha bo'yicha hamkorlik",
    message: "Tabiiy fanlar loyihasida birga ishlaymizmi?",
    date: "2025-01-14",
    status: "read",
  },
  {
    id: 7,
    sender: "Anora Sattorova",
    recipient: "Library",
    subject: "Kitob so'rovi",
    message: "Tadqiqotim uchun 'Fizika asoslari' kitobini so'rayman.",
    date: "2025-01-15",
    status: "unread",
  },
  {
    id: 8,
    sender: "Alisher Qodirov",
    recipient: "Maktab idorasi",
    subject: "Jadvalni o'zgartirish so'rovi",
    message: "Dars jadvalimdagi to'qnashuv sababli o'zgartirish so'rayman.",
    date: "2025-01-15",
    status: "unread",
  },
  {
    id: 9,
    sender: "Diyor Bek",
    recipient: "Sports Coach",
    subject: "Mashg'ulotlar jadvali",
    message: "Bu hafta basketbol mashg'uloti qachon bo'ladi?",
    date: "2025-01-15",
    status: "read",
  },
  {
    id: 10,
    sender: "Maktab direktori",
    recipient: "Barcha o'quvchilar",
    subject: "Muhim e'lon",
    message: "Talabalar qo'llanmasidagi yangilangan qoidalarni ko'rib chiqing.",
    date: "2025-01-16",
    status: "unread",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Matematika",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "Ingliz tili",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biologiya",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Fizika",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Kimyo",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "Tarix",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "Ingliz tili",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biologiya",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Fizika",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "Tarix",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Matematika",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biologiya",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Kimyo",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "Tarix",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Ingliz tili",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biologiya",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Fizika",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "Tarix",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Matematika",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "Ingliz tili",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Fizika",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Kimyo",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "Tarix",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];

export const studentSubjectsData = [
  { id: 1, studentId: 1, subject: "Matematika", score: 78, maxScore: 100 },
  { id: 2, studentId: 1, subject: "Ingliz tili", score: 84, maxScore: 100 },
  { id: 3, studentId: 1, subject: "Fizika", score: 72, maxScore: 100 },
  { id: 4, studentId: 2, subject: "Matematika", score: 91, maxScore: 100 },
  { id: 5, studentId: 2, subject: "Ingliz tili", score: 88, maxScore: 100 },
  { id: 6, studentId: 3, subject: "Biologiya", score: 64, maxScore: 100 },
  { id: 7, studentId: 3, subject: "Kimyo", score: 59, maxScore: 100 },
  { id: 8, studentId: 4, subject: "Tarix", score: 83, maxScore: 100 },
  { id: 9, studentId: 5, subject: "Musiqa", score: 95, maxScore: 100 },
  { id: 10, studentId: 6, subject: "Matematika", score: 70, maxScore: 100 },
];
